name: Format on Comment
on:
  issue_comment:
    types: [created]

jobs:
  format:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '@cargo format')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Run formatting
        run: |
          cargo fmt
          cargo clippy --fix --allow-dirty --allow-staged
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Auto-format code"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
